### ISSUE TITLE
UncaughtExceptionHandler looses events on crash

### ISSUE THREAD

**Issue by doapp-jeremiah** [matomo-org/matomo-sdk-android#249]
I installed the MatomoExceptionHandler using `TrackHelper.track().uncaughtExceptions().with(tracker)` and I can see the event being created and dispatched, but the app is being killed before the network request completes.

I'm attempt to debug this so I have the dispatch timeout currently set to 0 and I can see the following when the event is sent correctly (the [REMOVED] is my own edits):

```
1549581614.188 V/MATOMO:DefaultPacketSender: Connection is open to [REMOVED]
1549581614.188 V/MATOMO:DefaultPacketSender: Sending: Packet(type=GET, data=[REMOVED])
1549581614.970 V/MATOMO:DefaultPacketSender: Transmission finished (code=204).
```

When the crash happens I can see the first two lines but the app stops before the transmission is finished.

Is there a reason the dispatch has to be called in the exception handler as opposed to letting the event cache to disk and transmitting it on next app start up?

**Comment by d4rken** [comment]
The dispatch mechanism does not distinguish between specific types of data.

The default behavior is to attempt transmission and if that fails to cache the packets to disk and retry later. When writing that I didn't have exceptions in mind but focused on less resource usage.

So it seems the app killed too quickly for the exception to be dispatched?

I think the underlying is not the caching, but that the app is terminated early. We need to execute blockingly in the exception handler such that the app process is not before complete transmission.

Then again when do we stop blocking in non-successfull cases. Let's imagine there is a crash, but also connectivity issues, we shouldn't keep retrying but abort after 1 failure to transmit such that the app process can die.

Not sure yet how this would best be implemented. Thoughts?

**Comment by doapp-jeremiah** [comment]
I can see the behavior you describe.  I enabled the debug logging and I can see the event is drained from the cache, attempts to send, and the app terminates before success or failure.

I've worked with crash reporters in the past that assume the app won't be alive long enough to make a network request while crashing.  The approach there is to persist the event to disk and attempt to re-send the next time the app is initialized.

Is there a way to force a disk-write of the event before the VM is scrapped?

On the same note, is there a way to flush all outstanding events to disk?  I see the updateState in the EventCache but that seems to only trigger based on a failed attempt to fire the PacketSender.

What do you think of a blocking flush of the event queue to disk (including the exception event)?

**Comment by d4rken** [comment]
Bit busy with other projects atm.

So we basically have two features here:
* Write to disk first
* Create a blocking way to call `Tracker.track(...)`

I don't think there is a way to flush to disk atm, besides writing your own dispatcher module.

> What do you think of a blocking flush of the event queue to disk (including the exception event)?

The issue is that this kinda needs to be optional, we would only want this for exceptions, for all other events (which are the majority of events) we want it lightweight, e.g. don't cause disk IO and non-blocking.

**Comment by doapp-jeremiah** [comment]
Thanks again for looking at this.  I completely agree, the normal path should be as quick and light on resources as possible.

Do you take pull requests?  I've been looking at this over the last few days and I think I have a way to enable this without drastically changing how things work.

I'm thinking the dispatcher loop could be changed to tell the `EventCache` to write out events to the `EventDiskCache` in `PacketFactory.PAGE_SIZE` chunks.  Once the files are written out the dispatcher could read a file at a time through the `EventCache`, packetize it, and send it on the network.  Failures to send the packet would re-queue the block of events and re-write them to disk.

When the dispatcher is offline the loop would just write events to disk and skip the packetize and network submission.

This means the `EventCache` would loose the `updateState(...)` method as the disk write would be handled as part of the dispatcher loop.  `EventCache` and `EventDiskCache` would both need a way to read a single file's worth of events instead of doing a full drain.

This does cause a little more disk IO but it does it based on the dispatch interval which is already pushing IO.

Handling the second feature (blocking `Tracker.track(..)`) could be done by exposing a method on the tracker to "close" the tracker, which would put it in a manual offline mode and force a dispatch.  When the dispatch loop sees connectivity is in the manual override mode it can flush all events to the disk cache (ignoring the standard chunk size).  We could even include a synchronous close mode that joins the dispatch thread and blocks until events are in the cache.  The synchronous mode would be optional but useful in the uncaught exception path.

The part I'm not sure of is if this should be a different dispatcher or a replacement of the existing.  To make this work a small change needs to be made to `EventDiskCache` but everything else would be pretty easy to stand up as a different Dispatcher / EventCache if that was the better route to go.

**Comment by d4rken** [comment]
I do take pull requests but I tend to be quite picky :frowning: with core changes like this. I think we need to do a v5 (semver) too due to breaking changes in the cache API? Hm...

Thinking a bit out loud here to order my thoughts.

I think we should start with the introduction of function that allows for blocking tracking, because that's the base requirement to fix the exception tracking, then work inwards to improve handling of direct crashes (immediate process takedown) and non-connectivity periods while blocking.

My first idea was something like `track/submit(...., varargs*)` and add something like `TrackOptions.BLOCKING` for better compatibility and future enhancements, but your idea with a `close()` call sounds good too, though we'd need an `open()` too?

Maybe something `setMode(Mode.ONLINE/Mode.OFFLINE)` which affects caching, the uncaught exception handler does `setMode(Mode.OFFLINE)` before tracking the exception which would then mean that the tracked-exception is directly written to disk, whereas in `State.ONLINE` mode the tracked events go into RAM first, and only after failure to disk... Maybe a `Mode.ASSUME_OFFLINE` which would act like a "to-disk" strategy+direct transmission attempt.

Any changes to `EventDiskCache` need to stay compatible with files in existing deployment.

Overall saving to disk first is still not nice, I/O is among the most impacting things on Android (copy a large file, it will grind the OS to a halt on low end devices, more so than any CPU op).

> The part I'm not sure of is if this should be a different dispatcher or a replacement of the existing. To make this work a small change needs to be made to `EventDiskCache` but everything else would be pretty easy to stand up as a different Dispatcher / EventCache if that was the better route to go.

I would prefer to replace/update the current ones as the uncaught exception handler not working is a bug which would be good to fix for everyone, e.g. make the changes the new default...

Have you tested for how long the exception handler stays alive on a crash? E.g. block the handler, log something, count the time?

**Comment by doapp-jeremiah** [comment]
> I do take pull requests but I tend to be quite picky 😦 with core changes like this. I think we need to do a v5 (semver) too due to breaking changes in the cache API? Hm...

Completely understand (its a solid SDK, I'd be picky too).

> My first idea was something like `track/submit(...., varargs*)` and add something like `TrackOptions.BLOCKING` for better compatibility and future enhancements, but your idea with a `close()` call sounds good too, though we'd need an `open()` too?
> 
> Maybe something `setMode(Mode.ONLINE/Mode.OFFLINE)` which affects caching, the uncaught exception handler does `setMode(Mode.OFFLINE)` before tracking the exception which would then mean that the tracked-exception is directly written to disk, whereas in `State.ONLINE` mode the tracked events go into RAM first, and only after failure to > disk... Maybe a `Mode.ASSUME_OFFLINE` which would act like a "to-disk" strategy+direct transmission attempt.

I like the `setMode(...)` idea.  With that approach my `close()` idea looks like a shorthand for `setMode(Mode.OFFLINE)` followed by `forceDispatch()` and then some new mechanism that allows you to block or get a callback after the dispatch thread completes.  There would be no need to re-open the tracker as nothing is actually being closed.  Frankly, `close` was a bad name for the function as nothing is really closed out, I just couldn't think of a better name for it.

Would `Mode.OFFLINE` instantly write events to disk or wait for the dispatch interval?

> Any changes to `EventDiskCache` need to stay compatible with files in existing deployment.

Agreed.  Data migration is a pain.  The only change I was thinking about was to add a method that reads up to some limit instead of the full `drainTo`.  I'm unsure of the best limit mechanic.  If we control how many events go in each file the limit could be a single file.  If the events are written a bit more free form there could be a read until X events mechanism.  All of this would only be needed for the `Mode.ASSUME_OFFLINE`.

> Overall saving to disk first is still not nice, I/O is among the most impacting things on Android (copy a large file, it will grind the OS to a halt on low end devices, more so than any CPU op).

Yeah, I struggle with that.  The trade off is between performance and data consistency and I'm not sure how impactful the data writes will be as long as they are small and off the main thread.

> Have you tested for how long the exception handler stays alive on a crash? E.g. block the handler, log something, count the time?

Good thing to test, I'll try that out and see but I would guess any sort of timeout would be part of the platform and vary from device to device.  I know that the issue in this case is that the handler is calling the wrapped handler immediately after calling dispatch which starts a very quick clock on when the runtime is torn down.

> I think we should start with the introduction of function that allows for blocking tracking, because that's the base requirement to fix the exception tracking, then work inwards to improve handling of direct crashes (immediate process takedown) and non-connectivity periods while blocking.

Seems like the first steps would be to:

1. add `Tracker.setMode(Mode.ONLINE/Mode.OFFLINE)` as an override for the connectivity check in the dispatcher
2. add `Tracker.forceDispatchBlocking()` or some other named function that ensures it won't return until everything in the `EventCache` is written out
3. modify the existing `MatomoExceptionHandler` to `setMode(Mode.OFFLINE)`, track the event, and then call the new `forceDispatchBlocking()`

I think all that could be done with out changing the default behavior of anything outside of the exception handler.  Should also be doable without breaking any api.  Adding `Mode.ASSUME_OFFLINE` would force some `EventCache` changes but that part is more of an enhancement anyways.

**Comment by doapp-jeremiah** [comment]
I did a quick test and I can see that blocking the handler causes the ui to freeze up and will trigger ANR if you hold it long enough.

Exiting the method quickly without calling the wrapped handler appears to trigger the runtime shutdown normally (200 ms)

**Comment by d4rken** [comment]
Maybe it's best if you just start a PR on this and I'll review, I seem to not find time :disappointed: . Usually one get's a lot better insight into issues once some code starts flowing :)

> 1. add `Tracker.setMode(Mode.ONLINE/Mode.OFFLINE)` as an override for the connectivity check in the dispatcher
> 2. add `Tracker.forceDispatchBlocking()` or some other named function that ensures it won't return until everything in the `EventCache` is written out
> 3. modify the existing `MatomoExceptionHandler` to `setMode(Mode.OFFLINE)`, track the event, and then call the new `forceDispatchBlocking()`

That's my current idea too.

Some thoughts:
* I've shortly thought about making it only part of the Dispatcher API which would then mean it's all just a custom "Dispatcher", but because we need it as part of the `MatomoExceptionHandler` the `setMode` and `forceDispatchBlocking` need to be part of the tracker API.
* Is `OFFLINE` and `ONLINE` the best name for these modes? Are there any other modes that might be interesting?

> I did a quick test and I can see that blocking the handler causes the ui to freeze up and will trigger ANR if you hold it long enough.

So the maximum time we can block there is the ANR timer. Good to know!

**Comment by doapp-jeremiah** [comment]
> I've shortly thought about making it only part of the Dispatcher API which would then mean it's all just a custom "Dispatcher", but because we need it as part of the `MatomoExceptionHandler` the `setMode` and `forceDispatchBlocking` need to be part of the tracker API.

I was thinking the same.

> * Is `OFFLINE` and `ONLINE` the best name for these modes? Are there any other modes that might be interesting?

I thought `ONLINE` and `OFFLINE` weren't great names but the concept was clear and I figured the names would be easy to change later.  I'll play around with whatever makes sense as I'm coding it up.

I'm wrapping up something at the moment and I'll focus on this next.  Should have a PR for you to review in a day or two.
