### ISSUE TITLE
Wrong usage of user id, vistor id is not persisted

### ISSUE THREAD

**Issue by eyeled** [matomo-org/matomo-sdk-android#255]
The documentation at https://matomo.org/docs/user-id/ states that "The User ID must be the same for a given user across all her devices and browsers." Generating a random user id inside the SDK contradicts this. I think the user id should not be generated, but it should be left to the app to set it if applicable.
On the other hand the visitor is regenarated every time a Tracker instance is created. Quoting from the documentation again:  "Every unique visitor must be assigned a different ID and this ID must not change after it is assigned."

**Comment by d4rken** [comment]
> The documentation at https://matomo.org/docs/user-id/ states that "The User ID must be the same for a given user across all her devices and browsers." Generating a random user id inside the SDK contradicts this. I think the user id should not be generated, but it should be left to the app to set it if applicable.

The user id is generated once then persisted per app install, the default is random because it's good for privacy and allows the sdk to support tracking out of the box. You can easily set the user-id to an email if that's what you want. If we don't do this, then every time the app is opened, it count's as a new user towards your stats. Usually devices with apps are used by a single user.

> On the other hand the visitor is regenarated every time a Tracker instance is created. Quoting from the documentation again: "Every unique visitor must be assigned a different ID and this ID must not change after it is assigned."

The visitor id ties all tracked events toegether to make up a "session", which usually lasts for the duration the app is opened, so persisting it per tracker instance (e.g. while the app is in memory) seems to be a good choice to me.


I don't see how this is being used wrong?

**Comment by eyeled** [comment]
In the first place I stumbled upon this because the iOS SDK behaves differently than the Android SDK.
In the iOS SDK by default a visitor ID is randomly generated and persisted. No user ID is set by default.
In order to recognize returning visitors the visitor ID needs to stay the same. Cf. https://matomo.org/faq/general/faq_21418/
Regenerating it when the app is started again makes no sense to me. You won't recognize returning visitors.
The documentation states that the user ID must be the same for a given user *across all her devices and browsers*. That will never be the case for a generated random UUID.
So IMHO the iOS approach is how it should be done.

**Comment by d4rken** [comment]
> Regenerating it when the app is started again makes no sense to me. You won't recognize returning visitors.

AFAIK the server recognizes returning visitors also by their user-id too. At least it seems to work in my console. Are you sure that returning visitors are not tracked correctly with the Android SDK?

Your explanation makes sense though, looking at the commit history it seems like it just was always the way it currently is since 2014.

Changing this would make the default behavior (it can always be set manually) closer to iOS and easier for multiplatform setups.

So how do we change this without screwing everyone's statistics?

**Comment by NoyGri** [comment]
@d4rken @eyeled  The server's ability to define a session is based on a combination of the User's ID or its fingerprint (aka Config ID) (see #209 for more info about the fingerprint).

What happens when an event is sent to the server is roughly this:
1. If `userId` is defined, find the last event with the same `userId`. If an event was found AND it had occurred less then X minutes ago (configurable) then set the `idVisit` of the incoming event to be the same as the one of the retrieved event.
2. If the `userId` is null, repeat step 1 but with the provided `visitorId`
3. If also the `visitorId` is null OR the visitor ID was not found then repeat step 1 but with the `configId`

Note that the `visitorId` is simply a convenient way to recognize the same user from the same device during the same session in a fashion that is more certain than the `configId`.

> If you're really interested, follow these files' "breadcrumb trail" (start by looking for `getConfigHash` in the first file and then find the calling functions until you reach `findVisitor` on the last file):
> 1. https://github.com/matomo-org/matomo/blob/1a76568aa7f85920e8f4b58e0aa2fd32f64de8ad/core/Tracker/Settings.php
> 2. https://github.com/matomo-org/matomo/blob/master/plugins/CoreHome/Tracker/VisitRequestProcessor.php
> 3. https://github.com/matomo-org/matomo/blob/da7272436fdac34470987f60bba92aea21b9eabd/core/Tracker/VisitorRecognizer.php
> 4. https://github.com/matomo-org/matomo/blob/def74364a2d821d5dddaceece76c217547b99d14/core/Tracker/Model.php

The way I use the SDK is to start by setting the `userId` to `null` before the first event was sent, and force the `visitorId` to be hold the same value on every session. While this is indeed how the iOS and Web SDKs behaves, this is technically not required for Matomo to assign sessions correctly (after the session timeout passes it doesn't matter which `visitorId` was previously defined), but much more convenient when aggregating the data and deriving insights.

I am not familiar with the Matomo dashboard so there might be implications there that I'm not aware of.

@d4rken I believe you described the issue perfectly when you said "easier for multiplatform setups". 

I think the implementation should be: If the `userId` is not already presisted then set it to `null` by default. If the `userId` was already set then leave it untouched.
As for `visitorId` it should be added to the `SharedPreferences` file and allowed to be overwritten by the SDK's client, as it currently behaves. That way, in case a client is setting the `visitorId` every session as I do then their implementation won't be harmed and if they don't use it than no statistics would be harmed as anyways the visitorId wasn't persisted before and the user is most probably just interested in session information.
That means that it doesn't even have to be a major version.

**Comment by eyeled** [comment]
@NoyGri Your suggestion looks good to me. That would make the default behaviour more like the iOS SDK while keeping compatibility with existing code. But the behaviour would change for new app installations.

I was thinking about only persisting the `visitorId` and leaving it to the app's responsibility to set the `userId` to `null` after creating the Tracker instance.  Adding this code snippet as reference implementation should be enough so that new implementation would do it "right".

@d4rken Returning visitors are tracked correctly with the current implementation. They just look different than the iOS users in the visits log which drew my attention to the implementation details in the first place.

**Comment by d4rken** [comment]
See #256 for a changeset suggestion, is that what you had in mind?
