### ISSUE TITLE
Overriding MatomoApplication class is may not be the good way for initialization!!!

### ISSUE THREAD

**Issue by chainchelliah** [matomo-org/matomo-sdk-android#280]
This could be the enhancement issue or my suggestion. 

Extending your custom application class may leads to prevent the users to use of some other features like **SplitInstall** of Dynamic features If anyone may use it.  As we can't use many super types, this could cause many problem if your app class at scale. 

Also, I wonder why you choose java since you guys started development of this project recently,  I believe. Make use of **Kotlin** :)

**Comment by d4rken** [comment]
> Extending your custom application class may leads to prevent the users to use of some other features like SplitInstall of Dynamic features If anyone may use it. As we can't use many super types, this could cause many problem if your app class at scale.

The app class extension is just a convenient way for beginners to set it up, if you look at the code you'll see that you can just initialize it any way you want:

https://github.com/matomo-org/matomo-sdk-android/blob/v4.1.1/tracker/src/main/java/org/matomo/sdk/extra/MatomoApplication.java

https://github.com/matomo-org/matomo-sdk-android/blob/v4.1.1/tracker/src/main/java/org/matomo/sdk/Matomo.java#L40

> Also, I wonder why you choose java since you guys started development of this project recently, I believe. Make use of Kotlin :)

It's not a recent project :wink:. I'm not looking to just rewrite it because Java is now old and lame and Kotlin cool and hip (I love Kotlin, but I'd rather spend the time on projects I'm getting paid for :stuck_out_tongue: ).
