### ISSUE TITLE
Why auth_token for POST transmissions(Bulk processing) has been deprecated? Can we still implement this?

### ISSUE THREAD

**Issue by suada-haji** [matomo-org/matomo-sdk-android#321]
Hey all,
If we set `bulk_requests_require_authentication` to `1` in our `config` file, with the current implementation we are not able to add  `auth_token` for POST transmissions. 

This implementation [existed previously](https://github.com/d4rken/piwik-sdk-android/blob/b0ca273c97887d9ef854bdf147bf83bb449de90a/piwik-sdk/src/main/java/org/piwik/sdk/dispatcher/PacketFactory.java#L79) and was removed. Any thoughts how we can implement this now?

**Comment by d4rken** [comment]
Because it's not secure. 
The token would have to be stored client-side, in every users installation, and would be trivial to obtain.

You can pass anything manually as parameter to a `TrackMe` instance, but I strongly advise against it.

Further reading:
* https://matomo.org/faq/general/faq_114/
* https://github.com/matomo-org/matomo-sdk-ios/issues/99
